# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

joints:
  - right_hip_pitch
  - right_hip_roll
  - right_hip_yaw
  - right_knee
  - right_ankle_pitch
  - right_ankle_roll
